Repository the-collab-lab/tcl-69-smart-shopping-list, pull requests merged in 2024-04, with the labels that each got.

#67 [AM] Change welcome text from "Box Makers" to "Aisle Be There"
  src/views/Home.css
  src/views/Home.jsx
Labels: enhancement, design sprint

#71 [AM] Improve layout of list items and sub-sections
  src/components/ListItem.css
  src/components/ListItem.jsx
  src/index.css
  src/views/Home.css
  src/views/Home.jsx
  src/views/List.css
  src/views/List.jsx
Labels: enhancement, refactoring, design sprint

#75 [KD] [MF] Add delete button for lists
  src/api/firebase.js
  src/components/SingleList.jsx
Labels: enhancement, design sprint

#69 [AM] Change "Add your first item!" button
  src/views/List.css
  src/views/List.jsx
Labels: enhancement, design sprint

#73 Mf refactor v2
  src/components/AddItem.jsx
  src/components/AddItems.jsx
  src/components/SortedItemsMap.jsx
  src/components/index.js
  src/utils/data.js
  src/utils/index.js
  src/views/List.jsx
Labels: refactoring, design sprint

#78 [JH] Refactor list items from List to ManageList
  src/views/DeprecatedManageList.jsx
  src/views/List.jsx
  src/views/ManageList.jsx
Labels: refactoring, design sprint

#81 [JH] Update Link location in SingleList
  src/components/SingleList.jsx
Labels: bug fix, design sprint

#79 [KD] Change Footer heart emoji from red to purple
  src/views/Layout.jsx
Labels: design sprint

#86 [KD] Refactor Emoji component from About page
  src/components/Emoji.jsx
  src/components/index.js
  src/views/About.jsx
  src/views/Layout.jsx
Labels: enhancement, refactoring, design sprint

#84 [MF] Creates global color, btn, font styling
  src/components/Dialog.css
  src/index.css
  src/views/ManageList.jsx
Labels: design sprint, styling

#82 [KD] Stylize Header and Navbar
  index.html
  src/index.css
  src/views/Layout.css
  src/views/Layout.jsx
Labels: enhancement, design sprint

#88 [AM] Update home page
  index.html
  public/img/checkbox.png
  public/img/home-welcome-image.svg
  src/api/useAuth.css
  src/api/useAuth.jsx
  src/index.css
  src/views/About.css
  src/views/About.jsx
  src/views/Home.css
  src/views/Home.jsx
Labels: enhancement, design sprint

#92 [KD] Add screenshots of app on About page
  public/img/phone1.png
  public/img/phone2.png
  public/img/phone3.png
  public/img/phone4.png
  public/img/phone5.png
  src/views/About.jsx
Labels: design sprint

#90 [MF] styling list and items pages
  index.html
  src/api/index.js
  src/api/useAuth.jsx
  src/components/AddItem.jsx
  src/components/ListItem.css
  src/components/ListItem.jsx
  src/components/SingleList.css
  src/components/SingleList.jsx
  src/components/SortedItemsMap.css
  src/components/SortedItemsMap.jsx
  src/components/index.js
  src/favicon.ico
  src/index.css
  src/views/Home.css
  src/views/Home.jsx
  src/views/Layout.jsx
  src/views/List.css
  src/views/List.jsx
  src/views/ManageList.css
  src/views/ManageList.jsx
Labels: bug fix, refactoring, suggestion, design sprint, styling
