Repository the-collab-lab/tcl-69-smart-shopping-list, pull requests merged in 2024-03, with the labels that each got.

#27 [AM] [KD] Prevent Duplicates and Empty Item
  src/api/firebase.js
  src/views/ManageList.jsx
Labels: enhancement

#28 [MF] [JH] Estimate Next Purchase
  package-lock.json
  package.json
  src/api/firebase.js
  src/components/ListItem.jsx
  src/utils/dates.js
Labels: enhancement

#29 [KD] [JH] Sort Items By Urgency
  src/api/firebase.js
  src/views/List.jsx
Labels: enhancement

#32 [MF] Adding Router to List Name Buttons on Home Screen
  src/components/SingleList.jsx
Labels: enhancement, suggestion, design sprint

#41 [AM] Bug Fix For listPath
  src/views/List.jsx
Labels: bug fix

#43 [AM] Clear localStorage on signout, redirect to home
  src/api/useAuth.jsx
Labels: bug fix

#42 [AM] Add Return for updatedData.sort()
  src/api/firebase.js
Labels: warning fix

#39 [KD] Reduce List Items Label Size
  src/components/ListItem.css
  src/index.css
  src/views/List.css
  src/views/List.jsx
Labels: enhancement, suggestion, design sprint

#44 Upgrade NPM dependencies
  .eslintrc.json
  .husky/pre-commit
  package-lock.json
  package.json
  vite.config.js
Labels: security

#37 [MF] ShareListDialog to share list on List page
  .eslintrc.json
  src/App.jsx
  src/api/firebase.js
  src/components/AddItems.jsx
  src/components/Dialog.css
  src/components/Dialog.jsx
  src/components/ShareEmailInput.jsx
  src/views/List.css
  src/views/List.jsx
Labels: enhancement, design sprint

#50 [KD] Add Footer
  src/views/Layout.css
  src/views/Layout.jsx
Labels: enhancement, suggestion, design sprint

#52 [JH] Restrict Route Access
  src/views/List.css
  src/views/List.jsx
  src/views/ManageList.jsx
Labels: enhancement, suggestion, design sprint

#48 [MF] Add Item button that opens dialog on List.jsx WIP
  public/img/add-green.svg
  src/api/firebase.js
  src/components/Dialog.css
  src/components/ShareEmailInput.jsx
  src/views/List.css
  src/views/List.jsx
Labels: enhancement, design sprint

#56 [AM] Create Landing Page
  public/img/checkbox.png
  src/App.jsx
  src/views/Home.css
  src/views/Home.jsx
  src/views/Layout.jsx
  src/views/List.jsx
  src/views/ManageList.jsx
Labels: enhancement, design sprint

#61 [JH] Bug fix for items search bar
  src/views/List.jsx
Labels: bug fix

#62 [KD] Change the copy on 'About' Page
  src/views/About.jsx
Labels: suggestion, design sprint

#64 [KD] Prevent "/" in List name
  src/api/firebase.js
Labels: enhancement, design sprint
